# -*- coding: utf-8 -*-
"""Usaco#2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeHO8tE73ZnjOelXF0xy42vTMlXCDbk2
"""

with open("gift1.in","r") as f:
  lines=f.readlines()

NP=int(lines[0].strip())

participants=[]
balances={}

for i in range(1, NP+1):
  name=lines[i].strip()
  participants.append(name)
  balances[name]=0

line_index=NP+1
while line_index<len(lines):
  giver=lines[line_index].strip()
  line_index+=1
  money, num_recipients=map(int, lines[line_index].strip().split())
  line_index+=1
  if num_recipients>0:
    gift_amount=int(money/num_recipients)
    leftover=money%num_recipients
    balances[giver] -= money
    balances[giver] += leftover
    for i in range(num_recipients):
        recipient = lines[line_index].strip()
        line_index += 1
        balances[recipient] += gift_amount
for person in participants:
  print(f"{person}:{balances[person]}")