# -*- coding: utf-8 -*-
"""Usaco#1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YtXAR5BfdMWlFoTc8_iMlErXMJ0DifGK
"""

def main():
  with open("ride.in", "r") as infile:
    comet = infile.readline().strip()
    group = infile.readline().strip()
  print(comet)
  print(group)
  sum_comet=1
  sum_group=1
  for char in comet:
    sum_comet*=get_letter_position(char)
    print(get_letter_position(char))
  for char in group:
    sum_group*=get_letter_position(char)
    print(get_letter_position(char))
  mod_47_comet=sum_comet % 47
  mod_47_group=sum_group % 47
  print(mod_47_comet)
  print(mod_47_group)
  if(mod_47_comet==mod_47_group):
    print("GO")
  else:
    print("STAY")
def get_letter_position(letter):
    return ord(letter) - ord('A') + 1

main()