# -*- coding: utf-8 -*-
"""Usaco#5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qd8jlS2Lfi5qQqXNhOd3f6RTGc3MqGxo
"""

def add_stall(stall_indices,stalls):
  curr_dist=0
  max_dist=0
  curr_index=0
  max_index=-1

  for i in range(0,len(stall_indices)):
    if i==0:
      curr_dist=stall_indices[0]-1
      if curr_dist != -1:
        if(curr_dist>max_dist):
          max_dist=curr_dist
          max_index=0
      curr_dist=(stall_indices[i+1]-stall_indices[i])//2
      if(curr_dist>max_dist):
          max_dist=curr_dist
          max_index=(stall_indices[i]+stall_indices[i+1])//2
    elif i==len(stall_indices)-1:
      curr_dist=len(stalls)-stall_indices[i]-1
      if(curr_dist>max_dist):
          max_dist=curr_dist
          max_index=len(stalls)-1
    else:
      curr_dist=(stall_indices[i+1]-stall_indices[i])//2
      if(curr_dist>max_dist):
          max_dist=curr_dist
          max_index=(stall_indices[i]+stall_indices[i+1])//2
  stall_indices.append(max_index)
  stalls[max_index]=1
  stall_indices.sort()


with open('socdist1.in', 'r') as file:
    lines = file.readlines()

total_stalls=int(lines[0])
stall_status=lines[1]
stalls=[]

for stall in stall_status:
  stalls.append(int(stall))

stall_indices=[]

for i in range(len(stalls)):
  if stalls[i]==1:
    stall_indices.append(i)

for i in range(2):
  add_stall(stall_indices,stalls)

curr_dist=0
min_dist=stall_indices[i+1]-stall_indices[i]-1

for i in range(len(stall_indices)-1):
  curr_dist=stall_indices[i+1]-stall_indices[i]-1
  if curr_dist<min_dist:
    min_dist=curr_dist

print(min_dist)

print(stall_indices)